export const FETCH_USER_SALT = 'FETCH_USER_SALT';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const USER_LOGOUT = 'USER_LOGOUT';
export const COMMIT_DEVICEINFO = 'COMMIT_DEVICEINFO';
export const COMMIT_DEVICEINFO_FAILED = 'COMMIT_DEVICEINFO_FAILED';
export const FETCH_SEARCH_LIST = 'FETCH_SEARCH_LIST';
export const RECEIVE_SEARCH_LIST = 'RECEIVE_SEARCH_LIST';